before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: XX+o2Q2WfcvWiqcOxSTqW/o7cpJdG32OK+uo0LpX/yERBUeeVVE2dE4Wx++Hj4Q+2Oxkiil4gpPjBuho2iduV+wPCfnU69k/roMUEbXtcLt/kkxEkMyFxiFsSEThTMhLcsxdcLJN46/7NI/2FzUfVE3Sf6cVFhLL1h9qS4i+6dWCdYyVew6Kbw1g08Qi8f5eNm2aSNv5re7Vp29sOjZaGBBJ8FFFz/8B4tFJ6mCD+aFibUk6yBhh2Mk5e5ukAW7HTSLtESRQcb9u5VeUbJ/GnLX+KndKgVmMIhgKhXQcJpC9N/DihvNMdFoKZKzDEQnWOVIK+drQLqbzji9DHiqPlgTZqIWKuhKWfCgiwCsCkMEKGxVe6rRCA9OMrw1ferKTKPsJpPzQQmg+GKrGORdt8+o/cSanazwHlnjwgpS0VL+3d2ZLwoVSiHWs/4V8VXSQYhBOAHhsqKtsCcsJnqVu+MKQgFxpsXz2c9O2BnP2oy+qcOqKn5Wk3/vKWECpTtRA7KynA8No44M9IHVpEi63mjyeazhwSyRzC29YbwWoIigimQdYVckiKuiABl0BVeSPoq5F2Ln/qY9tt0yhndQ+SVjXol4xNO4EIHSLvswPne864EN81fSNDvqlImcZ7HiJY+h8AAe/2oiIPQoFee2knh6fu/Pa6wmBufPSQLJbLWY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
